### ISSUE TITLE
reliability

### ISSUE THREAD

**Issue by ipere** [yaozhaosh/chisel-aes#1]
Hi, 
I get you are using ECB mode.
Did you try to compare your results with software implementation ?
because I tried your implementation with a 128 bit key and 128 text
key = 1f1e1d1c1b1a19181716151413121110
text = ffeeddccbbaa99887766554433221100

the result is ecad5400be15fbaddedf35bc7fcccda5 for software and 28aa69b4dfb04138f7141c184128ee60 for your implementation

I am wondering from where the difference comes.

Thanks in advance

**Comment by yaozhaosh** [comment]
Hi,

Sorry for the late response. I have been overworking for several weeks...

I think I know where the difference comes. The key=1f1e1d1c1b1a19181716151413121110 means the first byte of key is 0x1f so in the design key[7:0]=0x1f. The same is for the plain text and cipher text between software and RTL (hardware) design.

The output from testbench:
key:      101112131415161718191a1b1c1d1e1f
text:     112233445566778899aabbccddeeff
cipher:   a5cdcc7fbc35dfdeadfb15be0054adec
invCipher:112233445566778899aabbccddeeff

It shows the design is correct. 

Hope it helps.

Thanks
Yao

**Comment by yaozhaosh** [comment]
And make sure you set Nk=4 in the test.
