### ISSUE TITLE
4 modules using AES

### ISSUE THREAD

**Issue by ipere** [yaozhaosh/chisel-aes#2]
Hi, 
I am using AesTop inside a module Encryption. 
`Module(new AesTop(4, false, 1, 0))`
I have four instanciations of this  module Encryption. 

When I let the 4 encryption modules I have an error of sink and source while running sbt appearing at the line where I call the new AesTop. 
But when I let only one encryption module everything works fine.

Do I have to change some parameters ? (for me encEngNum was only for one module, not if we are using several AesTop modules) 

Thanks

**Comment by yaozhaosh** [comment]
Hi ipere,
Parallel several modules means several times circuit logics, which means you need more RAM to run it. I once encountered similar problems. Would you try it using a PC (or a server) with more RAM?
Thanks
Yao
